version: "3.8"

services:
  web:
    build:
      context: .
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
    env_file:
      - .env

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  celery:
    restart: always
    build:
      context: .
    command: celery -A config worker --pool=solo -l info
    volumes:
      - ./src:/app
    env_file: .env
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
    command: celery -A config beat -l info
    volumes:
      - ./src:/app
    env_file: .env
    depends_on:
      - celery

volumes:
  postgres_data: